baseURL = "https://lukeh17.github.io/"
languageCode = "en-us"
title = ""
theme = "kross-hugo"
summaryLength = "10"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

# menu
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2

#[[menu.main]]
#URL = "resume"
#name = "Resume"
#weight = 3

# default parameters
[params]
home = "Home"
logo = ""

# theme color
theme_color = "#000000"

# contact info
phone = "(704) 706 7063"
email = "luke.honnold@drake.edu"
address = "3841 54th St Des Moines IA 50310"

# meta description
author = "Luke Honnold"
description = ""

# google analytics
google_analytics_id = "" # Your ID

# copyright
copyright = "&copy; 2021"

# preloader
[params.preloader]
enable = true
preloader = "uploads/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = ""
map_longitude = ""
map_marker = ""

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site
[[params.social]]
icon = "ti-github"
URL = "https://github.com/lukeh17"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/luke-honnold-982631180/"
